In [1]:
import pandas as pd
import requests

In [2]:
url="https://api.census.gov/data/2016/acs/acs1/subject?get=group(S2301)&for=school%20district%20(unified)&in=state:06"

In [3]:
response = requests.get(url)
response

In [4]:
response_json = response.json()

In [5]:
unifiedschool_df = pd.DataFrame(response_json,columns=response_json[0]).drop(0)
unifiedschool_df

,S2301_C01_001E,S2301_C01_001M,S2301_C01_002E,S2301_C01_002M,S2301_C01_003E,S2301_C01_003M,S2301_C01_004E,S2301_C01_004M,S2301_C01_005E,S2301_C01_005M,...,S2301_C04_033EA,S2301_C04_033MA,S2301_C04_034M,S2301_C04_034EA,S2301_C04_034MA,S2301_C04_035M,S2301_C04_035EA,S2301_C04_035MA,state,school district (unified)
1,82334,4632,7344,1421,7934,1797,8480,2166,6168,1891,...,None,None,3.0,None,None,4.1,None,None,06,00014
2,63598,2883,3681,951,7632,1699,4124,1000,4183,1073,...,None,None,1.4,None,None,1.4,None,None,06,00016
3,63453,2915,4177,1202,7082,2242,5533,1194,4657,1508,...,None,None,3.4,None,None,8.5,None,None,06,00017
4,62993,2307,3080,847,2450,880,4117,994,3726,956,...,None,None,2.9,None,None,1.9,None,None,06,00020
5,100634,5304,6860,1418,8242,1723,11608,2429,9154,1883,...,None,None,2.0,None,None,3.7,None,None,06,00027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,105964,4565,9016,1824,9117,2186,11195,1768,10446,1597,...,None,None,2.5,None,None,3.1,None,None,06,41160
114,120959,5772,7958,1885,12594,2436,12939,2389,10536,2015,...,None,None,1.7,None,None,1.3,None,None,06,41190
115,57114,1488,3821,909,4667,806,5024,778,4561,520,...,None,None,2.9,None,None,6.8,None,None,06,43470
116,190354,5874,19115,2318,19266,3038,16697,2813,18016,2753,...,None,None,3.9,None,None,1.4,None,None,06,84500
117,61066,7403,7618,1945,5785,1673,5519,1515,6582,1904,...,None,None,4.3,None,None,6.8,None,None,06,91135

In [7]:
unifiedschool_df.loc[unifiedschool_df["NAME"]=="Hesperia Unified School District, California"]

KeyError: 'NAME'