In [2]:
import pandas as pd
import requests

In [3]:
url="https://api.census.gov/data/2015/acs/acs1/subject?get=group(S2301)&for=school%20district%20(unified)&in=state:06"

In [4]:
response = requests.get(url)
response

In [5]:
response_json = response.json()

In [6]:
unifiedschool_df = pd.DataFrame(response_json,columns=response_json[0]).drop(0)
unifiedschool_df

,S2301_C01_001E,S2301_C01_001M,S2301_C01_002E,S2301_C01_002M,S2301_C01_003E,S2301_C01_003M,S2301_C01_004E,S2301_C01_004M,S2301_C01_005E,S2301_C01_005M,...,S2301_C04_033EA,S2301_C04_033MA,S2301_C04_034M,S2301_C04_034EA,S2301_C04_034MA,S2301_C04_035M,S2301_C04_035EA,S2301_C04_035MA,state,school district (unified)
1,61495,1977,4532,1198,3391,779,2951,856,3734,966,...,None,None,3.1,None,None,2,None,None,06,00020
2,74447,4000,6268,1396,8331,1614,7532,1930,7639,1992,...,None,None,6.1,None,None,11.1,None,None,06,00014
3,63117,2492,2956,828,5461,1471,6083,1563,4999,1366,...,None,None,2,None,None,1.4,None,None,06,00016
4,60729,2759,5469,1196,6212,1557,2906,968,5404,1506,...,None,None,8.1,None,None,3.8,None,None,06,00017
5,100489,4419,9986,2127,6724,1508,8424,1764,10501,1853,...,None,None,2.8,None,None,4.3,None,None,06,00027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,117691,6091,8541,1924,10819,1816,13962,2405,10050,1755,...,None,None,3,None,None,2.5,None,None,06,41190
113,50191,1993,3825,888,4816,1246,4783,945,4310,1060,...,None,None,4,None,None,2.3,None,None,06,43080
114,56119,1598,3186,759,5055,696,5812,475,5460,1038,...,None,None,6.1,None,None,4.9,None,None,06,43470
115,188288,5265,17229,1872,23521,3829,18685,2773,17406,2715,...,None,None,1.8,None,None,1,None,None,06,84500
116,68697,8578,6940,1770,9562,2403,7342,1700,6094,1532,...,None,None,3.9,None,None,13.1,None,None,06,91135

In [8]:
unifiedschool_df.loc[unifiedschool_df["NAME"]=="Hesperia Unified School District, California"]

KeyError: 'NAME'