In [1]:
pwd

'/Users/ellismok/Desktop/Challenges/ca-school-enrollment-trend'

In [2]:
# Dependencies and Setup
import pandas as pd
import pathlib
import csv
import scipy.stats as st
import numpy as np

In [3]:
# Create paths for csv

employment_unified_2019_data = "../Merged Employment/Resources/output_employment_data/Unified2019.csv"
employment_elementary_2019_data = "../Merged Employment/Resources/output_employment_data/Elementary2019.csv"
employment_secondary_2019_data = "../Merged Employment/Resources/output_employment_data/Secondary2019.csv"

In [4]:
# UNIFIED 2019

employment_unified_2019 = pd.read_csv(employment_unified_2019_data)
# pd.DataFrame(employment_unified_2019)

In [5]:
# ELEMENTARY 2019

employment_elementary_2019 = pd.read_csv(employment_elementary_2019_data)
# pd.DataFrame(employment_elementary_2019)

In [6]:
# SECONDARY 2019 

employment_secondary_2019 = pd.read_csv(employment_secondary_2019_data)
# pd.DataFrame(employment_secondary_2019)

In [7]:
list_of_files = [
    "../Merged Employment/Resources/output_employment_data/Unified2019.csv",
    "../Merged Employment/Resources/output_employment_data/Elementary2019.csv",
    "../Merged Employment/Resources/output_employment_data/Secondary2019.csv"
]

# Format pd.read_csv(filename).assign(year=2019)
employment_2019_df = []
for i,filename in enumerate(list_of_files):
    X1 = pd.read_csv(filename)
    X1["year"] = 2019
    employment_2019_df.append(X1)
    
# Combine the data into a single dataset
employment_2019_data = pd.concat(employment_2019_df)
employment_2019_merged = pd.DataFrame(employment_2019_data)

In [8]:
# Save csv file 

employment_2019_merged.to_csv("../Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2019.csv")

In [9]:
employment_2019_merged

,Unnamed: 0,Estimate!!Total!!Population 16 years and over,Estimate!!Total!!Population 20 to 64 years,Estimate!!Employment/Population Ratio!!Population 16 years and over,Estimate!!Employment/Population Ratio!!Population 20 to 64 years,Estimate!!Unemployment rate!!Population 16 years and over,Estimate!!Unemployment rate!!Population 20 to 64 years,NCESDist,year,School District Type
0,1,103753,73833,56.9,73.7,6.0,5.2,632070,2019,Unified
1,2,205097,155464,64.0,77.7,3.0,2.7,632550,2019,Unified
2,3,215389,163980,59.6,71.6,4.8,4.4,633150,2019,Unified
3,4,87017,63374,60.3,73.7,6.8,6.5,633750,2019,Unified
4,5,274468,205929,60.0,75.1,6.2,5.5,633840,2019,Unified
...,...,...,...,...,...,...,...,...,...,...
39,40,137172,106224,57.4,68.9,9.6,8.5,624660,2019,Secondary
40,41,211497,158512,55.7,69.3,7.3,6.8,625150,2019,Secondary
41,42,96912,75135,67.0,79.8,2.9,2.7,626310,2019,Secondary
42,43,74329,46552,51.5,71.1,2.1,2.4,626880,2019,Secondary
43,44,263863,197839,61.3,74.9,4.7,4.5,629270,2019,Secondary