In [1]:
pwd

'/Users/ellismok/Desktop/Challenges/ca-school-enrollment-trend/Yearly Merged Employment Workbook'

In [2]:
# Dependencies and Setup
import pandas as pd
import pathlib
import csv
import scipy.stats as st
import numpy as np

In [5]:
# Create paths for csv

employment_2015_data = "Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2015.csv"
employment_2016_data = "Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2016.csv"
employment_2017_data = "Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2017.csv"
employment_2018_data = "Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2018.csv"
employment_2019_data = "Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2019.csv"

In [8]:
list_of_files = [
    "../Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2015.csv",
    "../Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2016.csv",
    "../Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2017.csv",
    "../Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2018.csv",
    "../Merged Employment/Resources/merged_employment_yearly/Merged_Employment_2019.csv"
]

# Format pd.read_csv(filename).assign(year=2015)
all_merged_df = []
for i,filename in enumerate(list_of_files):
    X1 = pd.read_csv(filename)
    X1["year"] = 2015
    all_merged_df.append(X1)
    
# Combine the data into a single dataset
all_employment_data = pd.concat(all_merged_df)
all_employment_df = pd.DataFrame(all_employment_data)

In [9]:
all_employment_df

,Unnamed: 0,Unnamed: 0.1,Total!!Estimate!!Population 16 years and over,Total!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN!!White alone,Total!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN!!Black or African American alone,Total!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN!!American Indian and Alaska Native alone,Total!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN!!Asian alone,Total!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN!!Native Hawaiian and Other Pacific Islander alone,Total!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN!!Some other race alone,Total!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN!!Two or more races,...,Estimate!!Unemployment rate!!Population 16 years and over!!RACE AND HISPANIC OR LATINO ORIGIN!!Two or more races,Estimate!!Total!!Population 16 years and over!!RACE AND HISPANIC OR LATINO ORIGIN!!Hispanic or Latino origin (of any race),Estimate!!Employment/Population Ratio!!Population 16 years and over!!RACE AND HISPANIC OR LATINO ORIGIN!!Hispanic or Latino origin (of any race),Estimate!!Unemployment rate!!Population 16 years and over!!RACE AND HISPANIC OR LATINO ORIGIN!!Hispanic or Latino origin (of any race),"Estimate!!Total!!Population 16 years and over!!RACE AND HISPANIC OR LATINO ORIGIN!!White alone, not Hispanic or Latino","Estimate!!Employment/Population Ratio!!Population 16 years and over!!RACE AND HISPANIC OR LATINO ORIGIN!!White alone, not Hispanic or Latino","Estimate!!Unemployment rate!!Population 16 years and over!!RACE AND HISPANIC OR LATINO ORIGIN!!White alone, not Hispanic or Latino",Estimate!!Total!!Population 20 to 64 years,Estimate!!Employment/Population Ratio!!Population 20 to 64 years,Estimate!!Unemployment rate!!Population 20 to 64 years
0,0,1,74447.0,61671.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,5861.0,-999999999.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,63117.0,38791.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,3,60729.0,49133.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,4,61495.0,38338.0,-999999999.0,-999999999.0,17354.0,-999999999.0,-999999999.0,-999999999.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5,100489.0,66259.0,-999999999.0,-999999999.0,-999999999.0,-999999999.0,20013.0,-999999999.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,39,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-999999999.0,73871.0,58.6,11.5,42216.0,59.0,6.0,106224.0,68.9,8.5
212,40,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-999999999.0,83936.0,57.7,10.0,97033.0,53.4,6.3,158512.0,69.3,6.8
213,41,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-999999999.0,-999999999.0,-999999999.0,-999999999.0,48404.0,65.7,2.8,75135.0,79.8,2.7
214,42,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-999999999.0,-999999999.0,-999999999.0,-999999999.0,64206.0,49.5,2.5,46552.0,71.1,2.4
215,43,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-999999999.0,148123.0,66.4,4.3,78181.0,53.5,3.9,197839.0,74.9,4.5